import { Cpu, Database, Server, Video } from 'lucide-react';
import { scenarios } from '../data/demoData';
import { img } from '../utils/imagePath';

export default function DigitalTwin(){return <div className="page"><div className="page-heading"><div><p className="eyebrow">CAMERAS • DEVICES • CORRELATION</p><h1>Cameras & digital twin</h1><p>Every camera is connected to its branch, security zones, sensors and operating procedures.</p></div><div className="toolbar"><button className="button primary"><Video size={14}/>1,198 live</button><button className="button"><Cpu size={14}/>800 devices</button></div></div>
<section className="metrics"><div className="metric green"><label>Camera availability</label><strong>99.83%</strong><small>2 devices require attention</small></div><div className="metric"><label>ACS integrations</label><strong>250</strong><small>All pilot branches connected</small></div><div className="metric"><label>SAS zones</label><strong>412</strong><small>Strong room and perimeter</small></div><div className="metric"><label>Analysis cache hit rate</label><strong>94.6%</strong><small>No repeat vision-token cost</small></div></section>
<div className="grid-main" style={{marginBottom:12}}><section className="panel"><div className="panel-head"><h2>Representative branch twin</h2><span>FORT BRANCH • MUMBAI</span></div><div className="panel-body" style={{padding:0}}><img src={img('/images/digital-twin.png')} onError={e=>{e.currentTarget.style.display='none'}} alt="SBI branch digital twin" style={{width:'100%',height:300,objectFit:'cover',display:'block'}}/><div className="flow" style={{padding:14}}><span>Entrance CAM-01</span><b>→</b><span>Frisking zone</span><b>→</b><span>ACS door</span><b>→</b><span>Teller hall</span><b>→</b><span>Strong room</span></div></div></section><aside className="panel"><div className="panel-head"><h2>Prototype → production</h2><Server size={14}/></div><div className="panel-body architecture"><div className="arch-row"><div className="arch-node cloud">Cloudflare Worker</div><div className="arch-arrow">→</div><div className="arch-node">On-prem AI gateway</div></div><div className="arch-row"><div className="arch-node cloud">Supabase Postgres</div><div className="arch-arrow">→</div><div className="arch-node">On-prem PostgreSQL</div></div><div className="arch-row"><div className="arch-node cloud">Private Storage</div><div className="arch-arrow">→</div><div className="arch-node">SBI object storage</div></div><div className="arch-row"><div className="arch-node cloud">Gemini / Mistral</div><div className="arch-arrow">→</div><div className="arch-node">Approved model endpoints</div></div><div className="callout"><strong>Corrigendum aligned</strong><p>The cloud stack is presentation infrastructure only. The interfaces and data contracts remain portable to SBI’s on-prem environment.</p></div></div></aside></div>
<section className="scenario-grid">{scenarios.map(s=>{
  const poster=img(`/images/scenarios/${s.id.toLowerCase()}-clean.png`);
  return <article className="scenario-card" key={s.id}><video muted loop playsInline preload="metadata" poster={poster} src={img(`/media/scenarios/${s.video}`)} onMouseEnter={e=>void e.currentTarget.play()} onMouseLeave={e=>{e.currentTarget.pause();e.currentTarget.currentTime=0}}/><div className="scenario-copy"><strong>{s.name}</strong><small>{s.id} • {s.source}</small><div className="scenario-meta"><span className="badge">{s.status}</span><span style={{fontSize:9,color:'#5d6970'}}>Hover to preview</span></div></div></article>;
})}</section></div>}
