import { CheckCircle2, Play, Send, ShieldAlert, UserRoundCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useIncidents } from '../context/IncidentContext';
import type { IncidentStatus } from '../types';

const next:Record<IncidentStatus,IncidentStatus|undefined>={triggered:'acknowledged',acknowledged:'under_action',under_action:'resolved',resolved:'closed',closed:undefined};
export default function IncidentWorkspace(){const {incidentId}=useParams();const navigate=useNavigate();const {incidents,updateStatus,assign}=useIncidents();const selected=useMemo(()=>incidents.find(i=>i.id===incidentId)||incidents[0],[incidents,incidentId]);const [confirmed,setConfirmed]=useState(false);const [analysis,setAnalysis]=useState<{summary:string;confidence:number}|null>(null);const [analysisState,setAnalysisState]=useState('ready');const videoUrl=import.meta.env.DEV?'/__evidence/primary.mp4':'';const advance=()=>{const n=next[selected.status];if(n&&confirmed){updateStatus(selected.id,n,`Operator confirmed ${n.replace('_',' ')} after reviewing linked evidence and ${selected.sop}.`);setConfirmed(false)}};
const analyze=async()=>{if(!videoUrl||analysisState==='analyzing')return;setAnalysisState('analyzing');try{const blob=await(await fetch(videoUrl)).blob();const buffer=await blob.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buffer);const sha=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const worker=import.meta.env.VITE_WORKER_URL;if(!worker)throw new Error('Worker URL missing');const response=await fetch(`${worker}/api/video/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetId:'PRIMARY_CCTV_001',mimeType:'video/mp4',sha256:sha,durationSeconds:11,videoBase64:btoa(binary)})});if(!response.ok)throw new Error(`Analysis failed (${response.status})`);const payload=await response.json() as {cached:boolean;result:{summary:string;confidence:number}};setAnalysis(payload.result);setAnalysisState(payload.cached?'cached':'live');}catch(error){console.error(error);setAnalysisState('degraded')}};
return <div className="page"><div className="page-heading"><div><p className="eyebrow">INCIDENT MANAGEMENT SYSTEM</p><h1>Incident workspace</h1><p>Evidence, decisions and SLA clocks in one auditable workflow.</p></div><div className="toolbar"><button className="button" onClick={()=>assign(selected.id,'OPR-792')}><UserRoundCheck size={14}/>Assign to me</button><button className="button dark" disabled={!confirmed||!next[selected.status]} onClick={advance}><CheckCircle2 size={14}/>{next[selected.status]?`Move to ${next[selected.status]?.replace('_',' ')}`:'Lifecycle complete'}</button></div></div>
<div className="incident-layout"><aside className="panel incident-menu"><div className="panel-head"><h2>Priority queue</h2><span>{incidents.length}</span></div>{incidents.map(i=><div key={i.id} className={`incident-mini ${i.id===selected.id?'active':''}`} onClick={()=>navigate(`/incidents/${i.id}`)}><span className={`badge ${i.severity}`}>{i.severity}</span><strong style={{marginTop:7}}>{i.title}</strong><small>{i.id} • {i.ageMinutes} min</small></div>)}</aside>
<section className="stack"><div className="panel"><div className="panel-head"><h2>{selected.id} • {selected.camera}</h2><button className="button primary" style={{padding:'6px 9px'}} disabled={!videoUrl||analysisState==='analyzing'} onClick={()=>void analyze()}>{analysisState==='analyzing'?'ANALYZING VIDEO…':'ANALYZE WITH GEMINI'}</button></div><div className="video-shell">{videoUrl&&selected.id==='SBI-INC-00421'?<video controls src={videoUrl}/>:<div className="video-empty"><div><Play size={28} style={{margin:'0 auto 8px'}}/>Private evidence preview<br/><small>Signed media URL required</small></div></div>}<div className="camera-label">{selected.camera} • {selected.evidenceTime} IST</div><div className="ai-stamp">{analysisState==='live'?'LIVE ANALYSIS':analysisState==='degraded'?'DEGRADED • RULES ONLY':'CACHED ANALYSIS'} • {analysis?.confidence||selected.confidence}% CONFIDENCE</div></div><div className="detail-grid"><div><label>Location</label><strong>{selected.branch}</strong></div><div><label>Classification</label><strong>{selected.useCase} • {selected.severity}</strong></div><div><label>Assignee</label><strong>{selected.assignee}</strong></div></div></div>
<div className="panel"><div className="panel-head"><h2>AI pre-classification</h2><span>HUMAN VALIDATION REQUIRED</span></div><div className="panel-body"><div className="callout"><strong>{selected.title}</strong><p>{analysis?.summary||selected.summary}</p></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:12}}>{selected.signals.map(s=><span className="badge" key={s}>{s}</span>)}</div></div></div></section>
<aside className="stack"><section className="panel"><div className="panel-head"><h2>Operator decision</h2><ShieldAlert size={14}/></div><div className="panel-body"><span className={`badge ${selected.status}`}>{selected.status.replace('_',' ')}</span><p style={{fontSize:11,lineHeight:1.6}}>Review evidence and the recommended SOP before changing incident state.</p><label style={{display:'flex',gap:8,fontSize:10,lineHeight:1.4}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm the evidence has been reviewed and approve this audited action.</label></div></section><section className="panel"><div className="panel-head"><h2>{selected.sop}</h2><Send size={14}/></div><div className="panel-body"><ol style={{fontSize:10,lineHeight:1.8,paddingLeft:17}}><li>Acknowledge within {selected.slaMinutes} minutes.</li><li>Launch associated live camera and verify scene.</li><li>Notify branch authority and LHO supervisor.</li><li>Preserve evidence and record operator disposition.</li></ol></div></section><section className="panel"><div className="panel-head"><h2>Immutable timeline</h2><span>{selected.timeline.length} EVENTS</span></div><div className="panel-body timeline">{selected.timeline.map((e,k)=><div className="timeline-item" key={k}><time>{e.time}</time><strong>{e.label}</strong><p>{e.detail}</p><small>{e.actor}</small></div>)}</div></section></aside></div></div>}
