import { Bot, CheckCircle2, Database, Search, Send, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useIncidents } from '../context/IncidentContext';

type Message={role:'user'|'ai';text:string};
const prompts=['Which branches repeatedly missed frisking this month?','Why was SBI-INC-00421 escalated?','Compare acknowledgement SLA by circle.'];
export default function OperatorAgent(){const {incidents}=useIncidents();const [messages,setMessages]=useState<Message[]>([{role:'ai',text:'I am the SBI CMS Operator Agent. I can search incidents, reconstruct evidence timelines, compare operational KPIs and retrieve RFP-aligned SOPs. Any state-changing action remains subject to your explicit approval.'}]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);
const localAnswer=(q:string)=>{const l=q.toLowerCase();if(l.includes('00421')||l.includes('escalated'))return `SBI-INC-00421 was classified CRITICAL under U.17 at 14:38:31 IST. Video observations (person approaching teller; staff huddle) were correlated with panic-zone activity. The 2-minute acknowledgement SLA and SOP-U17-PANIC-01 require immediate LHO supervisor escalation.\n\nSources: SBI-INC-00421 timeline 14:38:31–14:38:35; SOP-U17-PANIC-01.`;if(l.includes('frisk'))return `Mumbai LHO has the strongest repeat pattern: BKC, Fort and Andheri East recorded 14 incomplete-frisking incidents this month, 9 involving missing lower-leg checkpoints. BKC breached acknowledgement SLA twice.\n\nSources: U.12 incident cohort; SOP-U12-FRISK-02; representative pilot data.`;if(l.includes('compare')||l.includes('sla'))return `Acknowledgement SLA compliance: Chennai 96.2%, Mumbai 93.8%, New Delhi 92.4%, Kolkata 91.7%, Lucknow 89.6%. Critical U.17 compliance is 97.1% overall; device-health incidents are the main source of ageing.\n\nSources: SLA compliance view, 01 Aug–03 Sep 2026.`;return `I found ${incidents.length} relevant live incidents. The highest operational priority is SBI-INC-00421 (U.17, critical), followed by SBI-INC-00418 (U.12, high). Review linked evidence before approving any action.\n\nSources: current incident queue; RFP use cases U.12 and U.17.`};
const send=async(q=input)=>{if(!q.trim()||busy)return;setInput('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const worker=import.meta.env.VITE_WORKER_URL as string|undefined;if(worker){const r=await fetch(`${worker}/api/agent/query`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});if(!r.ok)throw new Error('Agent unavailable');const data=await r.json() as {answer:string};setMessages(m=>[...m,{role:'ai',text:data.answer}]);}else{await new Promise(r=>setTimeout(r,550));setMessages(m=>[...m,{role:'ai',text:localAnswer(q)}]);}}catch{setMessages(m=>[...m,{role:'ai',text:`Live Mistral endpoint is unavailable. Demo retrieval result:\n\n${localAnswer(q)}`}]);}finally{setBusy(false)}};
return <div className="page"><div className="page-heading"><div><p className="eyebrow">MISTRAL • GROUNDED FUNCTION CALLING</p><h1>Agentic operator</h1><p>Ask operational questions in natural language; every answer preserves evidence provenance.</p></div><span className="badge"><ShieldCheck size={12}/> Human approval enforced</span></div><div className="agent-layout"><section className="panel chat-panel"><div className="panel-head"><h2><Bot size={14} style={{display:'inline',marginRight:7}}/>SBI CMS Operator Agent</h2><span>{busy?'QUERYING TOOLS…':'READY'}</span></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><small>{m.role==='ai'?'Operator agent • grounded':'LHO supervisor'}</small>{m.text}</div>)}{busy&&<div className="message ai"><small>Tool execution</small>Searching incidents and approved SOP corpus…</div>}</div><div className="suggestions">{prompts.map(p=><button key={p} onClick={()=>void send(p)}>{p}</button>)}</div><div className="chat-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Ask about incidents, evidence, SLA or SOP…"/><button className="button primary" onClick={()=>void send()} disabled={!input.trim()||busy}><Send size={14}/>Send</button></div></section><aside className="panel"><div className="panel-head"><h2>Verified tool surface</h2><Database size={14}/></div>{[['search_incidents','Filter 7,500 incident records by scope, type and time.'],['get_incident_timeline','Reconstruct evidence and operator decisions.'],['get_operational_kpis','Query indexed SLA and availability views.'],['search_sops','Hybrid keyword + pgvector retrieval.'],['mutating actions','Requires confirmation token; always audited.']].map(([n,d],i)=><div className="tool-card" key={n}><strong>{i<4?<Search size={11} style={{display:'inline',marginRight:6}}/>:<CheckCircle2 size={11} style={{display:'inline',marginRight:6}}/>}{n}</strong><p>{d}</p></div>)}</aside></div></div>}
